version: 1.0.{build}
skip_tags: true
image: Visual Studio 2019 Preview
branches:
  only:
  - master
before_build:
- ps: dotnet restore
# Install dotnet core 3.0 latest (alpha!!), as this is not provided on AppVeyor yet
install:
- ps: Invoke-WebRequest https://download.microsoft.com/download/9/0/1/901B684B-659E-4CBD-BEC8-B3F06967C2E7/NDP471-DevPack-ENU.exe -OutFile NDP471-DevPack-ENU.exe
- ps: Start-Process -FilePath "NDP471-DevPack-ENU.exe" -ArgumentList "/q","/norestart" -Wait
- ps: Start-FileDownload 'https://dotnetcli.blob.core.windows.net/dotnet/Sdk/master/dotnet-sdk-latest-win-x64.exe'
- ps: Start-Process .\dotnet-sdk-latest-win-x64.exe "/install /norestart /quiet /log sdkinstall.log" -NoNewWindow -Wait
build:
  publish_aspnet_core: true
  verbosity: minimal