version: 1.0.{build}
skip_tags: true
image: Visual Studio 2019 Preview
branches:
  only:
  - master
before_build:
- ps: dotnet restore
# Install dotnet core 3.0 latest (alpha!!), as this is not provided on AppVeyor yet
install:
- ps: Start-FileDownload 'https://download.visualstudio.microsoft.com/download/pr/4d2dfaa1-4f9c-4526-bb6f-117d9d8bbd0e/a9fc9994c1b4d485ab41632b81bf4f56/dotnet-sdk-3.0.100-preview6-012264-win-x64.exe'
- ps: Start-Process .\dotnet-sdk-3.0.100-preview6-012264-win-x64.exe "/install /norestart /quiet /log sdkinstall.log" -NoNewWindow -Wait
build:
  publish_aspnet_core: true
  verbosity: minimal